services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/app?createDatabaseIfNotExist=true
      - DB_NAME=app
      - DATABASE_USER=root
      - DATABASE_PWD=root_pass
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
